## 0.Alpha
- 프레임워크 : 프로그램 흐름 제어를 프레임워크가 한다.
- 라이브러리 : 개발자가 직접 흐름을 직접 제어한다.

## 1.GPU 사용
- 파이토치 하면서 GPU사용하는 방법은 사용자가 고민안해도 되는건가?
- 파이토치는 사용자가 명시적으로 알려주지 않으면 기본적으로 모든 연산을 CPU에서 처리합니다.
- TensorFlow 같은 일부 프레임워크는 GPU가 있으면 자동으로 할당하기도 하지만, 파이토치는 "모든 제어권을 개발자에게 준다"는 철학을 가지고 있어서 데이터(Tensor)와 모델(Model)을 GPU 메모리로 직접 옮겨주어야 합니다.
- 파이토치에서 GPU를 쓰려면 보통 아래의 3단계 패턴을 무조건 작성하게 됩니다.

### 1). 1. GPU 장치 설정
- 먼저 현재 환경에서 GPU(CUDA)를 쓸 수 있는지 확인하고, 사용할 장치를 변수로 지정합니다.

``` python
import torch

# GPU가 사용 가능하면 'cuda', 아니면 'cpu'를 선택 (맥북 M1/M2/M3의 경우 'mps')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("사용 중인 장치:", device)
```

### 2). 데이터(Tensor)를 GPU로 이동
- 생성한 텐서에 .to(device)를 붙여 GPU 메모리로 보냅니다.

```python
x = torch.tensor([1.0, 2.0, 3.0])
x = x.to(device)  # x를 GPU로 이동

```

### 3). 모델을 GPU로 이동
- 마찬가지로 정의한 신경망 모델도 .to(device)로 GPU에 올려야 합니다.

``` python
model = MyModel()
model = model.to(device)  # 모델의 가중치들을 GPU로 이동
```

- 파이토치는 같은 장치에 있는 데이터끼리만 연산할 수 있기 때문에, [입력 데이터 + 모델 가중치]가 모두 동일한 GPU 메모리에 올라가 있는지 늘 확인하셔야 합니다.
- 결론적으로, "장치 지정(device) $\rightarrow$ 데이터와 모델을 .to(device)로 보내기" 이 패턴만 기억하고 계시면 됩니다!


## 2. 텐서 이해하기
- 하나의 숫자는 스칼라
- 스칼라를 모아 1차원 묶음은 벡터
- 이를 다시 2차원 배열로 만든 것을 매트릭스 , 행렬
- 행렬을 쌓아 3차원으로 만든 것을 텐서라고 한다.
- 텐서 : 3차원 이상의 숫자 배열을 의미.
-
- 파이썬 리스트는 각 원소의 데이터 타입을 유지시킨 상태로 저장이 가능하나,
- 파이토치 텐서는 하나의 텐서에 하나의 데이터 타입만 사용할 수 있습니다.

In [2]:
# 1.텐서와 리스트 차이
import torch

data= [1,0.3, True]
print("list : " ,data)
print("tensor : ", torch.tensor(data))

list :  [1, 0.3, True]
tensor :  tensor([1.0000, 0.3000, 1.0000])


In [6]:
# 2. 텐서 생성

import torch

t= torch.tensor([1.,3.,5.,7.,9.,4.]) # 실수연산이 기본. 계산 이점 때문에 디폴트.
print(t)
터

tensor([1., 3., 5., 7., 9., 4.])


In [9]:
print(t.dim()) # rank
print(t.shape) # shape
print(t.size()) # shape

1
torch.Size([6])
torch.Size([6])


In [10]:
print(t[0], t[3],t[-1] ) # 원소 접근
print(t[1:4], t[3:-1]) # 슬라이싱
print(t[:3],t[4:]) # 슬라이싱

tensor(1.) tensor(7.) tensor(4.)
tensor([3., 5., 7.]) tensor([7., 9.])
tensor([1., 3., 5.]) tensor([9., 4.])


In [11]:
t= torch.tensor([[1.,3.,5.],
                [7.,9.,11.],
                [2.,4.,6.],
                [8.,10.,12.]])
print(t)

tensor([[ 1.,  3.,  5.],
        [ 7.,  9., 11.],
        [ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [12]:
print(t.dim())
print(t.shape)

2
torch.Size([4, 3])


In [14]:
# 3. 텐서 생성법 
# 기본 함수 : 출력 텐서의 모양을 입력 받아 텐서를 반환
# _like 함수 : 다른 텐서를 입력 받아 입력 텐서와 같은 모양의 텐서를 반환
# (매번 텐서 크기를 지정하기 힘드니까 입력 텐서랑 같은 크기로 만듬.)

# empty 함수 : 임의의 값으로 채워져 있음
t= torch.empty([3,4])
print(t)
print(torch.empty_like(t))
print(torch.empty(t.shape))

tensor([[ 0.0000e+00,  0.0000e+00,  9.0450e+21,  3.0823e-41],
        [ 1.1387e+21,  3.0823e-41, -1.0264e-18,  4.5680e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[ 0.0000e+00,  0.0000e+00,  8.2210e+21,  3.0823e-41],
        [ 1.1387e+21,  3.0823e-41, -8.4883e-19,  4.5680e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[9.0446e+21, 3.0823e-41, 9.8729e+19, 3.0823e-41],
        [3.8115e-43, 0.0000e+00, 8.9683e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [15]:
# zeros 함수
t= torch.zeros([3,2,2])
t1= torch.zeros_like(t)
print(t)
print(t1)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [16]:
# ones 함수
t= torch.ones([2,3,4])
t1= torch.ones_like(t)
print(t)
print(t1)


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [17]:
# full : 특정 값으로 채워진 텐서를 반환
t= torch.full([1,2,4],7) # [1,2,4] 는 채널, 행, 열 크기를 지정하는 것.
t1=torch.full_like(t,9)
print(t)터
print(t1)

tensor([[[7, 7, 7, 7],
         [7, 7, 7, 7]]])
tensor([[[9, 9, 9, 9],
         [9, 9, 9, 9]]])


In [22]:
# random 
print(torch.rand([3,4]) )# rand :[0,1)의 범위에서 랜덤한 값으로 채워진 텐서를 생성합니다.

tensor([[0.3863, 0.9309, 0.5742, 0.7079],
        [0.0093, 0.2179, 0.2182, 0.2508],
        [0.3796, 0.7546, 0.6030, 0.9903]])


In [23]:
print(torch.randn([2,3])) # randn : 평균 0, 분산 1인 표준 정규 분포 값으로 채워진 텐서를 생성합니다.


tensor([[-1.9698, -0.6678,  0.4435],
        [-0.3436, -0.7131,  0.5927]])


In [24]:
print(torch.randint(0,5,[2,4]))
# randint : 정수형 텐서 반환, [low,high]범위의 균일 분포 값으로 채워진 정수형 텐서를 생성
# 함수는 범위의 최소값, 최대값, 생성할 텐서의 모양을 입력으로 받는다.


tensor([[4, 0, 0, 0],
        [0, 3, 3, 0]])


In [25]:
# arange : 연속적인 숫자 텐서를 반환. 범위 시작, 범위 끝, 간격 이 3가지를 인자로 받는다.
print(torch.arange(0,16))
print(torch.arange(start=0, end = 16, step =2))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14])


In [26]:
# 브로드캐스팅
t1 = torch.tensor([[1,3]])
t2 = torch.tensor([[2,2]])
print(t1 + t2)
print(t1.add(t2))
print(torch.add(t1,t2))


tensor([[3, 5]])
tensor([[3, 5]])
tensor([[3, 5]])


In [27]:
t1 = torch.tensor([[1,3]])
t2 = torch.tensor([[2]]) # [2] => [[2,2]]
print(t1 + t2)

tensor([[3, 5]])


In [28]:

t1 = torch.tensor([[1, 3]])              # shape: (1, 2) => 브로드캐스팅 후 [[1, 3], [1, 3]]
t2 = torch.tensor([[2], [4]])            # shape: (2, 1) => 브로드캐스팅 후 [[2, 2], [4, 4]]

print(t1 + t2)

tensor([[3, 5],
        [5, 7]])


In [29]:
t = torch.arange(12).reshape(3,2,2)
print(t.shape)
print(t)
print(t.sum()) # 전체 합


torch.Size([3, 2, 2])
tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])
tensor(66)


In [30]:
print(t.sum(dim=0)) # 0번째 차원을 기준으로 합
print(t[:,0,0], t[:,0,0].sum())
print(t[:,0,1], t[:,0,1].sum())
print(t[:,1,0], t[:,1,0].sum())
print(t[:,1,1], t[:,1,1].sum())

# 이와 비슷하게 사용되는 함수들.
# mean(), var(),std(),var_mean(), std_mean(), max(),min(), argmax(),argmin()

tensor([[12, 15],
        [18, 21]])
tensor([0, 4, 8]) tensor(12)
tensor([1, 5, 9]) tensor(15)
tensor([ 2,  6, 10]) tensor(18)
tensor([ 3,  7, 11]) tensor(21)


In [31]:
print(t.flatten())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [32]:
# 텐서 차원 조작 
# reshape : 텐서의 모양을 변환하는데 가장 많이 사용되는 함수.

t = torch.tensor([[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]])

print(t)
print(t.shape)


tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.Size([2, 2, 3])


In [33]:
print(t.reshape([4,3]))
print(t.reshape([4,3]).shape)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
torch.Size([4, 3])


In [34]:
# permute : 데이터 순서는 그대로 유지한 채 차원 간의 위치를 바꾸어 주는 함수이다.
t= torch.tensor([[[1.,2.,3.],[4.,5.,6.]]])
print(t)
print(t.shape)


tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
torch.Size([1, 2, 3])


In [35]:
# squeeze : 크기가 1인 차원을 제거하는 함수.
t = torch.rand([3,1,4,1])
print(t.squeeze().shape)
print(t.squeeze(dim=1).shape)
print(t.reshape([3,4]).shape)


torch.Size([3, 4])
torch.Size([3, 4, 1])
torch.Size([3, 4])


In [36]:
# unsqueeze


In [38]:
# 텐서 합치기
# cat
x= torch.randn(2,3)
print(x)
print(torch.cat((x,x,x), dim=0)) # 첫 인자 : 결합하고자 하는 텐서, 두번째 인자 : 어떤 차원인지.
print(torch.cat((x,x,x),0).shape)

tensor([[-0.4649,  1.3102,  0.5870],
        [-1.8045,  0.5351, -1.0630]])
tensor([[-0.4649,  1.3102,  0.5870],
        [-1.8045,  0.5351, -1.0630],
        [-0.4649,  1.3102,  0.5870],
        [-1.8045,  0.5351, -1.0630],
        [-0.4649,  1.3102,  0.5870],
        [-1.8045,  0.5351, -1.0630]])
torch.Size([6, 3])


In [39]:
print(torch.cat((x,x,x),1))
print(torch.cat((x,x,x),1).shape)

tensor([[-0.4649,  1.3102,  0.5870, -0.4649,  1.3102,  0.5870, -0.4649,  1.3102,
          0.5870],
        [-1.8045,  0.5351, -1.0630, -1.8045,  0.5351, -1.0630, -1.8045,  0.5351,
         -1.0630]])
torch.Size([2, 9])


In [42]:
# stack
# 기존 텐서들을 새로운 차원으로 생성한 후 생성된 차원을 기준으로 합치는 함수

x = torch.randn(2,)
print(x)
print(torch.stack((x,x,x)))
print(torch.stack((x,x,x)).shape)


tensor([-0.2210, -0.0938])
tensor([[-0.2210, -0.0938],
        [-0.2210, -0.0938],
        [-0.2210, -0.0938]])


## 3.Pandas

- lib_md에서 정리한다.

## 4.Matplotlib
- lib_md에서 정리한다.